server:
  port: ${RESOURCE_SERVER_PORT:8081}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth/realms/first-realm}
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

crm:
  host-address: http://localhost:8081
  oauth2:
    users:
      server-uri: ${USERS_SERVER_URI:http://localhost:8080/auth/admin/realms/first-realm/users}
      default-pw: ${DEFAULT_PW:pass123}
